---
# Definition of connected endpoints in the fabric.
servers:
  # Name of the defined server.
  - name: leaf1-2-server1
    # Definition of adapters on the server.
    adapters:
        # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [PCI1, PCI2]
        # Device ports where the server ports are connected.
        switch_ports: [Ethernet2, Ethernet2]
        # Device names where the server ports are connected.
        switches: [leaf1, leaf2]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          # The port-channel name on the endpoint that will be used in the port-channel description.
          endpoint_port_channel: Bond1
          # Port channel mode for LACP.
          mode: active

  - name: leaf3-4-server1
    adapters:
      - endpoint_ports: [PCI1, PCI2]
        switch_ports: [Ethernet2, Ethernet2]
        switches: [leaf3, leaf4]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          mode: active