---
#FABRIC.yml

# Configuration specifically for deployment tasks using eAPI
ansible_connection: httpapi
ansible_network_os: eos
ansible_user: ansible
ansible_password: ansible
ansible_httpapi_port: 443
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false

# Aggressive timeout settings for cEOS containers
ansible_command_timeout: 300
ansible_connect_timeout: 120
persistent_command_timeout: 300
persistent_connect_timeout: 120
ansible_httpapi_session_key:
  validate_certs: false

# AVD Fabric Name
fabric_name: FABRIC

# AVD Design Variables
design:
  type: l3ls-evpn

# Documentation
eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

# Routing protocols
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true

# BGP peer groups
bgp_peer_groups:
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# P2P interfaces MTU (1500 for containerlab)
p2p_uplinks_mtu: 1500

# Interface mappings
default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    downlink_interfaces: [Ethernet1-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet10-14]
    mlag_interfaces: [Ethernet8-9]
  - types: [l2leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]

# CVP not needed in containerlab!
